### ISSUE TITLE
Did not build default/sound

### ISSUE THREAD

**Issue by NHQ** [xk/node-sound#2]
Hello, I tried your module on node 0.4.12 on Mac OSX 10.6.7.

```
NHQ:xk-node-sound elenagragasin$ node-waf configure build clean
Setting srcdir to                        : /Users/elenagragasin/webdev/xk-node-sound 
Setting blddir to                        : /Users/elenagragasin/webdev/xk-node-sound/build 
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (1.177s)
Waf: Entering directory `/Users/elenagragasin/webdev/xk-node-sound/build'
[1/2] cxx: sound.cc -> build/default/sound_1.o
[2/2] cxx_link: build/default/sound_1.o -> build/default/sound.node
Waf: Leaving directory `/Users/elenagragasin/webdev/xk-node-sound/build'
'build' finished successfully (7.270s)
'clean' finished successfully (0.005s)
```

In fact it did not build default/sound.node or any other file there.

```
Error: Cannot find module './build/default/sound'
    at Function._resolveFilename (module.js:326:11)
    at Function._load (module.js:271:25)
    at require (module.js:355:19)
    at Object.<anonymous> (/Users/elenagragasin/webdev/xk-node-sound/test-sinewave.js:46:12)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)
    at Array.<anonymous> (module.js:430:10)
    at EventEmitter._tickCallback (node.js:126:26)
NHQ:xk-node-sound elenagragasin$ 
```

**Comment by xk** [comment]
Hi,

You're doing a node-waf configure build clean: you've got to remove that clean at the end because it's deleting the module !

**Comment by NHQ** [comment]
Oh! 

The readme says node-waf clean build, but when google translated the page, it changed to node-waf build clean.

I re-built and heard the test tones! All right!

**Comment by xk** [comment]
Ok. Enjoy !

**Comment by xk** [comment]
Hey, now it works with (almost) any version of node, up to the latest (0.6.6).
